### ISSUE TITLE
Pool queue release seems to be broken

### ISSUE THREAD

**Issue by kpoxas** [bda-research/node-crawler#121]
https://github.com/sylvinus/node-crawler/blob/master/lib/crawler.js#L81

All tasks in queue use the same identifier "1"
If I replace "1" it with queuedCount variable pooling is working fine.

**Comment by davidrissato** [comment]
A really QUICK fix to solve this problem is:
```diff
*** node_modules/crawler/lib/crawler.js
*** 96,102 ****
          max          : self.options.maxConnections,
          priorityRange: self.options.priorityRange,
          create       : function(callback) {
<             callback(1);
>             callback(null, new Date());
          },
          destroy      : function() {}
      });
```

I noticed that you are not using Pool as a factory, you are only using it to control your own instances.
No problem about that, but when you called your callback with a fixed number of 1, it created all poolReferences the same references (as @kpoxas rightly pointed), because the Pool internally compare instances using `==`.
If you just change your code to return a `new Date()` for every instance, you will create different object instances, and everything will go fine.

With this simple change, you probably won't need to control queueItemSize by yourself (that comment on line 128: `// Pool stats are behaving weird - have to implement our own counter`)

**Comment by mike442144** [comment]
it's a critical bug, please try new version, if any further question I'll reopen
