### ISSUE TITLE
Are there any performance information in the result?

### ISSUE THREAD

**Issue by unr3al011** [bda-research/node-crawler#145]
I am looking for some data like known from php curl: total_time, namelookup_time, connect_time,pretransfer_time, starttransfer_time and so on...

is there anything implementated yet?

**Comment by mike442144** [comment]
These info should provide by request I think. Maybe you can ask in the request issues.

**Comment by mike442144** [comment]
This is an old issue, now I can refer that `request.js` introduced the detailed timing phase in new version which you are interested in. Jump to the `time` option [here](https://github.com/request/request#requestoptions-callback) to find out what you want. Since that `crawler` has the super set options of `request.js`, we can easily get the timing phase by setting `time` to true.
