### ISSUE TITLE
localAddress is not passed to request call

### ISSUE THREAD

**Issue by timbowhite** [bda-research/node-crawler#155]
Looks like there's some code that chooses which options to pass to request(), and 'localAddress' isn't one of them.

```
    var requestArgs = ['uri','url','qs','method','headers','body','form','json','multipart','followRedirect',
        'followAllRedirects', 'maxRedirects','encoding','pool','timeout','proxy','auth','oauth','strictSSL',
        'jar','aws'];


    var req = request(_.pick.apply(this,[ropts].concat(requestArgs)), function(error,response) {
```

**Comment by mike442144** [comment]
@timbowhite I have fix this in my repo. Please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it. I'll continue to make it the best crawler in nodejs world.
