### ISSUE TITLE
after work success, program block 30second and exit?

### ISSUE THREAD

**Issue by wjx0912** [bda-research/node-crawler#172]
here is my source code:
```
var Crawler = require('crawler');
 
var crawler = new Crawler({
    maxConnections: 10,
    callback: function(err, result, $) {
        $('li').each(function(index, li) {
            console.log(index + ' :');
            console.log('time:' + $(li).children(0).text());
            console.log('url:' + result.uri + $(li).children(1).attr('href'));
            console.log('title:' + $(li).children(1).text());
        });
    }
});
 
crawler.queue('http://dev.guanghe.tv/category/tech/');
```

the program work normal, but after show normal result, it block 30second and exit, why?

**Comment by mike442144** [comment]
Yes, it works well even if the process has to wait 30 seconds before exits with `0` , which is the way how `pool` works in Crawler.

**Comment by wjx0912** [comment]
hi, mike442144,
thanks for your reply.

i just modify crawler.js:
`	self.pool = Pool({
		name: 'crawler',
		max: self.options.maxConnections,
		priorityRange: self.options.priorityRange,
		**idleTimeoutMillis : 1,			// mill second**`

the 'idleTimeoutMillis ' can add as a crawler option. thanks

**Comment by mike442144** [comment]
@wjx0912 That's cool, you got it. But actually, that means your pool will release in 1ms after idle. However, what a resource pool means?It is a pool hold resources and is acquired by user directly, if you release immediately after used, it is not a pool, for instance, in Java/C# world, you will use connection pool to hold connections to the MySQL server to improve performance since it will take much time and memory to create and release a connection.
So, the best solution is release all resources after you done.
```
onDrain:function(pool){
    pool.destroyAllNow();
}
```
You know when you done, right?

**Comment by wjx0912** [comment]
hi, mike442144,
thanks for your advice, i benefit a lot from it~~~

**Comment by mike442144** [comment]
You're welcome.
