### ISSUE TITLE
ES6 syntax and vscode typescript

### ISSUE THREAD

**Issue by cristovao-trevisan** [bda-research/node-crawler#256]
Hello,

the company I currently work at uses lots of crawlers, but they are all in Java. My team is now planning to build them in node and found your package.
We would like to keep your logic but add more stuff to it, the most important thing being promises and vscode typing support.
How would you fell if I implemented this using ES6 (babel) and typescript? In other words, how would you fell about a refactor that needs to be transpiled?

I will build a PR anytime soon if you think this a good way to go

**Comment by mike442144** [comment]
Hey guy, I'm glad to see you have adopt this package, It is a little bit difficult for this package to rewrite in typescript, because of the compatibility reason. 
Actually I'm considering that refactor the code to modern ecmascript version, say 6(obviously not compatible with low versions of node), also wanna introduce Promise feature. But I have some concerns, I also use Crawler in my company a lot in production environment, and I believe that you know that how many tasks have to be done in your Java system per second, imagine that if you use promise, how to handle huge number of failures and results? I have no idea, so pls tell me if you have any progress.

You know what? you have another choice, use [floodesh](https://github.com/bda-research/floodesh). it is powerful with scalability, availability and failure tasks retry feature. I think it is more suitable for a company use in production, because it is maintainable for your team. 
All in words it depends on you,  my only wish is that you can involve and help together improve our what ever package at the same time, feel free to ask if any questions :)
