### ISSUE TITLE
memory leaks with cheerio

### ISSUE THREAD

**Issue by Anthony-Mckale** [bda-research/node-crawler#301]
hi chaps was writing a simple crawler and was finding the node app was running out of memory about the 30k sites crawled mark
https://github.com/Anthony-Mckale/2019-mr-simple-crawler

think it's this issue
https://github.com/cheeriojs/cheerio/issues/856

found wrapping string returns from $ ... .text / .attr etc etc with this

let unleak = (s) => {
                if (!s) {
                   return '';
                }
                return (' ' + s).substr(1);
            };

solved the memory leak, 

hope this helps someone else

 ta

Anthony

**Comment by mike442144** [comment]
Thank you so much guy, this issue is `htmlparser2` related one and seems difficult to fix according to the discussion on `cheerio` repo. for a long time when we ran into the memory issue we use `whacko` as an alternative. in common cases cheerio is wonderful. I'll close this issue and any one could reopen if necessary.
