### ISSUE TITLE
drain event called multiple times

### ISSUE THREAD

**Issue by villesau** [bda-research/node-crawler#348]
Seems that with current version of Bottleneck `drain` event might be called multiple times. This happens at least if some of the requests fail.

Other case when drain is called more than once is when using grouping.

**Comment by mike442144** [comment]
I believe you do not `queue` the new task before `done` called in callback. You should check this your code, but if not you could paste the code in your convenience.
What do you mean by 'grouping'?

**Comment by villesau** [comment]
This probably happens because limited queueSize can go negative.

By grouping I mean `limiter` prop.

**Comment by mike442144** [comment]
Thank you for your reply,

1. we customized bottleneck package named `bottleneckP` which has priority included
1. we have thousands of scripts written base on `crawler` and this won't happen if code is written in the right way
1. better to post more details will help to find out the root cause. e.g. in what situation the `unfinishedClients` will go negative. As you can see we use it a lot in daily work, so it's good for me to know a corner case in which probably we'll have trouble.

**Comment by villesau** [comment]
@mike442144 the current version of Bottleneck also supports priority.

queueSize can go negative when the system retries failed calls. Also if multiple limiters are used, drain is called for each of them.

**Comment by mike442144** [comment]
Actually I don't think retry failed task will cause negative queueSize, each time we get error `done` will be called and queueSize - 1, then enqueue the task as usual, that means queueSize +1.
Which version are you using? I suggest you to adopt the latest version to test again and post your testing result here.

**Comment by mike442144** [comment]
close due to inactive, will reopen if any update
